test for production env

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -1,5 +1,8 @@
 name: Continuous Integration Pipeline
-'on': pull_request
+# Just for production env test.
+'on':   
+  release:
+    types: [published]
 env:
   PROJECT_ID: ${{ secrets.GKE_PROJECT }}
   GKE_CLUSTER: gke-testing-cluster
@@ -84,6 +87,7 @@ jobs:
     # Deploy the Docker image to the GKE cluster
     - name: Deploy
       run: |-
+        cd ci_service
         ./kustomize edit set image gcr.io/PROJECT_ID/IMAGE:TAG=gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA
         ./kustomize build . | kubectl apply -f -
         kubectl rollout status deployment/$DEPLOYMENT_NAME
@@ -151,69 +155,69 @@ jobs:
         exit_code=$?
         exit $exit_code
   
-  run-load-tests:
-    if: ${{ always() }}
-    needs: run-integration-tests
-    name: run load tests
-    runs-on: ubuntu-latest
+  # run-load-tests:
+  #   if: ${{ always() }}
+  #   needs: run-integration-tests
+  #   name: run load tests
+  #   runs-on: ubuntu-latest
 
-    steps:
-    - name: Checkout
-      uses: actions/checkout@v2
+  #   steps:
+  #   - name: Checkout
+  #     uses: actions/checkout@v2
 
-    # Setup gcloud CLI
-    - uses: google-github-actions/setup-gcloud@master
-      with:
-        version: '331.0.0'
-        service_account_key: ${{ secrets.GKE_SA_KEY }}
-        project_id: ${{ secrets.GKE_PROJECT }}
+  #   # Setup gcloud CLI
+  #   - uses: google-github-actions/setup-gcloud@master
+  #     with:
+  #       version: '331.0.0'
+  #       service_account_key: ${{ secrets.GKE_SA_KEY }}
+  #       project_id: ${{ secrets.GKE_PROJECT }}
 
-    # Configure Docker to use the gcloud command-line tool as a credential
-    # helper for authentication
+  #   # Configure Docker to use the gcloud command-line tool as a credential
+  #   # helper for authentication
 
-    - run: |-
-        gcloud --quiet auth configure-docker
-    - uses: google-github-actions/get-gke-credentials@main
-      with:
-        cluster_name: ${{ env.GKE_CLUSTER }}
-        location: ${{ env.GKE_ZONE }}
-        credentials: ${{ secrets.GKE_SA_KEY }}
-    - name: Build
-      run: |-
-        cd load_test
-        docker build \
-          --tag "gcr.io/$PROJECT_ID/load/$IMAGE:$GITHUB_SHA" \
-          --build-arg GITHUB_SHA="$GITHUB_SHA" \
-          --build-arg GITHUB_REF="$GITHUB_REF" \
-          .
-    - name: Publish
-      run: |-
-        docker push "gcr.io/$PROJECT_ID/load/$IMAGE:$GITHUB_SHA"
-    # Set up kustomize
-    - name: Set up Kustomize
-      run: |-
-        cd load_test
-        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
-        chmod u+x ./kustomize
-    - name: Deploy
-      run: |-
-        cd load_test
-        ./kustomize edit set image gcr.io/PROJECT_ID/load/IMAGE:TAG=gcr.io/$PROJECT_ID/load/$IMAGE:$GITHUB_SHA
-        ./kustomize build . | kubectl apply -f -
-        kubectl rollout status deployment/$DEPLOYMENT_NAME
-        kubectl get services -o wide
-    - name: load_test_log
-      run: |-
-        pods=$(kubectl get pods --selector=job-name=gke-test-load --output=jsonpath='{.items[*].metadata.name}')
-        kubectl wait --for=condition=complete job/gke-test-load --timeout=360s &
-        completion_pid=$!
-        kubectl wait --for=condition=failed job/gke-test-load --timeout=360s && exit 1 &
-        failure_pid=$! 
-        kubectl wait --for=condition=ContainersReady pods/$pods --timeout=240s
-        kubectl logs --follow job/gke-test-load
-        wait -n $completion_pid $failure_pid
-        exit_code=$?
-        exit $exit_code
+  #   - run: |-
+  #       gcloud --quiet auth configure-docker
+  #   - uses: google-github-actions/get-gke-credentials@main
+  #     with:
+  #       cluster_name: ${{ env.GKE_CLUSTER }}
+  #       location: ${{ env.GKE_ZONE }}
+  #       credentials: ${{ secrets.GKE_SA_KEY }}
+  #   - name: Build
+  #     run: |-
+  #       cd load_test
+  #       docker build \
+  #         --tag "gcr.io/$PROJECT_ID/load/$IMAGE:$GITHUB_SHA" \
+  #         --build-arg GITHUB_SHA="$GITHUB_SHA" \
+  #         --build-arg GITHUB_REF="$GITHUB_REF" \
+  #         .
+  #   - name: Publish
+  #     run: |-
+  #       docker push "gcr.io/$PROJECT_ID/load/$IMAGE:$GITHUB_SHA"
+  #   # Set up kustomize
+  #   - name: Set up Kustomize
+  #     run: |-
+  #       cd load_test
+  #       curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
+  #       chmod u+x ./kustomize
+  #   - name: Deploy
+  #     run: |-
+  #       cd load_test
+  #       ./kustomize edit set image gcr.io/PROJECT_ID/load/IMAGE:TAG=gcr.io/$PROJECT_ID/load/$IMAGE:$GITHUB_SHA
+  #       ./kustomize build . | kubectl apply -f -
+  #       kubectl rollout status deployment/$DEPLOYMENT_NAME
+  #       kubectl get services -o wide
+  #   - name: load_test_log
+  #     run: |-
+  #       pods=$(kubectl get pods --selector=job-name=gke-test-load --output=jsonpath='{.items[*].metadata.name}')
+  #       kubectl wait --for=condition=complete job/gke-test-load --timeout=360s &
+  #       completion_pid=$!
+  #       kubectl wait --for=condition=failed job/gke-test-load --timeout=360s && exit 1 &
+  #       failure_pid=$! 
+  #       kubectl wait --for=condition=ContainersReady pods/$pods --timeout=240s
+  #       kubectl logs --follow job/gke-test-load
+  #       wait -n $completion_pid $failure_pid
+  #       exit_code=$?
+  #       exit $exit_code
   
   delete-service:
     if: ${{ always() }}
@@ -234,9 +238,7 @@ jobs:
     - name: delete-service-gke
       run : |-
           kubectl delete deployment gke-test
-          kubectl delete job/gke-test-load
           kubectl delete job/gke-test-selenium
-          kubectl delete ingress gke-test-service
           kubectl delete service gke-test-service-backend
         
 
